# Check SQLite database (`excel_data.db`)

This notebook summarizes **everything persisted** by the app (`db_storage.init_db`): raw Excel structure (`files`, `sheets`, `columns`, `data`), graph edges (`relationships`), vectors (`embeddings`), and finalized S2T metadata (`source_tables`, `target_tables`, `column_mappings`, `additions`).

**Run location:** preferably from the project root (`etl-mapping-rag`) so `excel_data.db` is found next to `notebooks/` or in the cwd. Paths are resolved automatically.

**Note:** `relationships` can link endpoints in different ways depending on code path:
- `load_data_from_similarity_report` → `MAPS_TO` from **Excel `columns.column_hash`** to **`column_mappings.id`**;
- `schema_matcher.create_graph_edges_from_mapping` → `MAPS_TO` from **`columns`** to **`get_target_column_id(table, column)`** (not a DB row).

The checks below classify endpoints instead of assuming a single shape.

In [20]:
from __future__ import annotations

import sqlite3
from pathlib import Path
from IPython.display import display

import pandas as pd

# Application schema (matches db_storage.init_db)
EXPECTED_TABLES = (
    "files",
    "sheets",
    "columns",
    "data",
    "relationships",
    "embeddings",
    "source_tables",
    "target_tables",
    "column_mappings",
    "additions",
)


def resolve_db_path() -> Path:
    cwd = Path.cwd().resolve()
    candidates = [
        cwd / "excel_data.db",
        cwd.parent / "excel_data.db",  # if cwd is notebooks/
        cwd / ".." / "excel_data.db",
    ]
    for p in candidates:
        p = p.resolve()
        if p.is_file():
            return p
    return (cwd / "excel_data.db").resolve()


def connect_ro(db: Path) -> sqlite3.Connection:
    uri_path = db.as_posix()
    return sqlite3.connect(f"file:{uri_path}?mode=ro", uri=True)


DB_PATH = resolve_db_path()
print(f"Database: {DB_PATH}")
if not DB_PATH.is_file():
    raise FileNotFoundError(
        f"SQLite file not found: {DB_PATH}. Upload a workbook in the app or copy excel_data.db here."
    )

conn = connect_ro(DB_PATH)
conn.row_factory = sqlite3.Row

Database: /Users/nikolajabramov/PycharmProjects/etl-mapping-rag/excel_data.db

In [21]:
def list_user_tables(con: sqlite3.Connection) -> list[str]:
    q = """
    SELECT name FROM sqlite_master
    WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
    ORDER BY name
    """
    return [r["name"] for r in con.execute(q).fetchall()]


tables = list_user_tables(conn)
missing = [t for t in EXPECTED_TABLES if t not in tables]
extra = [t for t in tables if t not in EXPECTED_TABLES]
print("tables in sqlite_master:", tables)
print("missing vs app schema:", missing or "none")
print("extra tables (not in canonical list):", extra or "none")

tables in sqlite_master: ['additions', 'column_mappings', 'columns', 'data', 'embeddings', 'files', 'relationships', 'sheets', 'source_tables', 'target_tables']
missing vs app schema: none
extra tables (not in canonical list): none

In [22]:
rows = []
for t in sorted(set(EXPECTED_TABLES) | set(tables)):
    try:
        n = conn.execute(f'SELECT COUNT(*) AS n FROM "{t}"').fetchone()["n"]
    except sqlite3.DatabaseError:
        n = None
    rows.append({"table": t, "row_count": n})

counts_df = pd.DataFrame(rows).sort_values("table").reset_index(drop=True)
counts_df

             table  row_count
0        additions         25
1  column_mappings       1232
2          columns         96
3             data      17620
4       embeddings          0
5            files          1
6    relationships        900
7           sheets         10
8    source_tables         41
9    target_tables         98

## Referential sanity (SQLite has no FKs — we check orphans in SQL)

In [23]:
checks: list[tuple[str, str, int]] = []

checks_sql = [
    (
        "sheets -> files (missing file_hash)",
        """
        SELECT COUNT(*) AS n FROM sheets s
        LEFT JOIN files f ON f.file_hash = s.file_hash
        WHERE f.file_hash IS NULL
        """,
    ),
    (
        "columns -> sheets",
        """
        SELECT COUNT(*) AS n FROM columns c
        LEFT JOIN sheets s ON s.sheet_hash = c.sheet_hash
        WHERE s.sheet_hash IS NULL
        """,
    ),
    (
        "data.sheet_hash -> sheets",
        """
        SELECT COUNT(*) AS n FROM data d
        LEFT JOIN sheets s ON s.sheet_hash = d.sheet_hash
        WHERE s.sheet_hash IS NULL
        """,
    ),
    (
        "data.column_hash -> columns",
        """
        SELECT COUNT(*) AS n FROM data d
        LEFT JOIN columns c ON c.column_hash = d.column_hash
        WHERE c.column_hash IS NULL
        """,
    ),
    (
        "column_mappings.target_table_id -> target_tables",
        """
        SELECT COUNT(*) AS n FROM column_mappings cm
        LEFT JOIN target_tables t ON t.id = cm.target_table_id
        WHERE t.id IS NULL
        """,
    ),
    (
        "column_mappings.source_table_id -> source_tables",
        """
        SELECT COUNT(*) AS n FROM column_mappings cm
        LEFT JOIN source_tables st ON st.id = cm.source_table_id
        WHERE st.id IS NULL
        """,
    ),
]

for label, sql in checks_sql:
    n = conn.execute(sql).fetchone()["n"]
    checks.append((label, "orphan_rows", int(n)))

checks_df = pd.DataFrame(checks, columns=["check", "kind", "count"])
checks_df

                                              check         kind  count
0               sheets -> files (missing file_hash)  orphan_rows      0
1                                 columns -> sheets  orphan_rows      0
2                         data.sheet_hash -> sheets  orphan_rows      0
3                       data.column_hash -> columns  orphan_rows      2
4  column_mappings.target_table_id -> target_tables  orphan_rows      0
5  column_mappings.source_table_id -> source_tables  orphan_rows      0

In [24]:
# Precompute id sets for relationship endpoint typing
col_hashes = {r["column_hash"] for r in conn.execute("SELECT column_hash FROM columns")}
mapping_ids = {r["id"] for r in conn.execute("SELECT id FROM column_mappings")}

rel_summary = pd.read_sql_query(
    """
    SELECT relation_type AS type, COUNT(*) AS cnt
    FROM relationships GROUP BY relation_type ORDER BY cnt DESC
    """,
    conn,
)
rel_summary

           type  cnt
0       MAPS_TO  874
1  DERIVED_FROM   26

In [25]:
rows_eps = []
for row in conn.execute(
    "SELECT from_id, to_id, relation_type FROM relationships"
).fetchall():
    fid, tid = row["from_id"], row["to_id"]
    rows_eps.append(
        {
            "relation_type": row["relation_type"],
            "from_in_columns": fid in col_hashes,
            "to_in_columns": tid in col_hashes,
            "from_in_mappings": fid in mapping_ids,
            "to_in_mappings": tid in mapping_ids,
        }
    )

eps_df = pd.DataFrame(rows_eps)
if not eps_df.empty:
    frac_cols = [
        "from_in_columns",
        "to_in_columns",
        "from_in_mappings",
        "to_in_mappings",
    ]
    display(
        eps_df.groupby("relation_type")[frac_cols]
        .mean()
        .round(3)
        .rename(columns=lambda c: "frac_" + c)
    )
    # Rows where neither endpoint is a known column / mapping row (might be synthetic target column id)
    weird = eps_df[
        ~(
            (eps_df["from_in_columns"] | eps_df["from_in_mappings"])
            & (eps_df["to_in_columns"] | eps_df["to_in_mappings"])
        )
    ]
    print(
        "relationships with unresolved endpoints (empty if all edges touch DB columns/mappings):",
        len(weird),
    )
else:
    print("No relationships")

,frac_from_in_columns,frac_to_in_columns,frac_from_in_mappings,frac_to_in_mappings
relation_type,,,,
DERIVED_FROM,0.0,1.0,0.0,0.00
MAPS_TO,1.0,0.0,0.0,0.97

relationships with unresolved endpoints (empty if all edges touch DB columns/mappings): 52

## Source → mapping → target

Denormalized view of finalized S2T rows: **`source_tables`** and **`target_tables`** joined through **`column_mappings`**.

The second query adds Excel-side context when **`MAPS_TO`** links a `columns.column_hash` to a `column_mappings.id` (from `load_data_from_similarity_report`).

In [26]:
src_tgt_sql = """
SELECT
    st.name AS source_table,
    st.system_code AS source_system_code,
    st.description AS source_description,
    cm.source_column,
    tt.name AS target_table,
    cm.target_column,
    tt.description AS target_description,
    cm.transformation_rule,
    cm.data_type,
    cm.is_primary_key,
    cm.id AS mapping_id,
    cm.source_table_id,
    cm.target_table_id
FROM column_mappings cm
INNER JOIN source_tables st ON st.id = cm.source_table_id
INNER JOIN target_tables tt ON tt.id = cm.target_table_id
ORDER BY
    COALESCE(tt.name, ''),
    COALESCE(cm.target_column, ''),
    COALESCE(st.name, ''),
    COALESCE(cm.source_column, '')
"""

mapping_join_df = pd.read_sql_query(src_tgt_sql, conn)
print("rows (inner join source × mapping × target):", len(mapping_join_df))
display(mapping_join_df.head(50))

orph_cols = pd.read_sql_query(
    """
    SELECT COUNT(*) AS n FROM column_mappings cm
    LEFT JOIN source_tables st ON st.id = cm.source_table_id
    LEFT JOIN target_tables tt ON tt.id = cm.target_table_id
    WHERE st.id IS NULL OR tt.id IS NULL
    """,
    conn,
).iloc[0]["n"]
print("column_mappings rows missing source_tables or target_tables (should be 0):", int(orph_cols))

# Enrich with Excel columns when lineage MAPS_TO(column_hash -> mapping_id) exists
with_excel_sql = """
SELECT
    sh.sheet_name AS excel_sheet,
    c.column_index,
    c.column_name_flat AS excel_column_flat,
    st.name AS source_table,
    cm.source_column,
    tt.name AS target_table,
    cm.target_column,
    cm.id AS mapping_id,
    cm.transformation_rule
FROM column_mappings cm
INNER JOIN source_tables st ON st.id = cm.source_table_id
INNER JOIN target_tables tt ON tt.id = cm.target_table_id
LEFT JOIN relationships r ON r.to_id = cm.id AND r.relation_type = 'MAPS_TO'
LEFT JOIN columns c ON c.column_hash = r.from_id
LEFT JOIN sheets sh ON sh.sheet_hash = c.sheet_hash
ORDER BY
    excel_sheet,
    excel_column_flat,
    target_table,
    cm.target_column
"""

mapping_join_excel_df = pd.read_sql_query(with_excel_sql, conn)
_with_lineage = (
    mapping_join_excel_df["excel_column_flat"].notna()
    & (mapping_join_excel_df["excel_column_flat"] != "")
).sum()
print("enriched rows with Excel column lineage:", int(_with_lineage), "of", len(mapping_join_excel_df))
display(mapping_join_excel_df.head(50))

rows (inner join source × mapping × target): 1232

,source_table,source_system_code,source_description,source_column,target_table,target_column,target_description,transformation_rule,data_type,is_primary_key,mapping_id,source_table_id,target_table_id
0,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,bank_correspondentAccount_escrow_accountDetails,NaN,accountDetails.escrowAccount.bank.corresponden...,string,0,af7ee08b85809be93d01d44b7cc2b9ab,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
1,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,bankunitcode_beneficiary,NaN,beneficiary.bankUnitCode,string,0,44b49074708ddc29be708128fdefa9e9,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
2,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,closeDate_agreement,NaN,agreement.closeDate,date,0,85bd8d4c9187b8a89acf99f0dec86756,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
3,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,completeEstimateDate_agreementObject,NaN,agreementObject.completeEstimateDate,date,0,da04e5c7d8032ad454f8b8d30dd516c7,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
4,escrow_legal214_agreement_actual,None,None,deleted,escrow_legal214_agreement_actual_dto,deleted,NaN,NaN,boolean,0,10f6ce1427a877ac72132f8653d337a0,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
5,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,devLoanAgrKulId_agreement,NaN,agreement.developerLoanAgreementKulId,string,0,051e44c98fde56def0d7a11a14b2825e,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
6,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,devLoanAgr_EksId_agreement,NaN,agreement.developerLoanAgreementEksId,string,0,e9268e7f80f281229b56fc661e66d214,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
7,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,developerLoanAgrDate_cred_agreement,NaN,agreement.developerLoanAgreementDate,date,0,38b26fc317dc2744aac6467d3430ef81,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
8,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,developerLoanAgrNumber_cred_agreement,NaN,agreement.developerLoanAgreementNumber,string,0,d5d700e524a27bafe913f3d977efd732,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
9,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,eksAccountId_accountDetails,NaN,accountDetails.eksAccountId,string,0,114ea5c02492363cfe142ee729267d3f,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
10,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,escrowAmount_currency_agreement,NaN,agreement.escrowAmount.currency,string,0,8adeea0525a2e47395f349b457a634d0,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
11,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,escrowAmount_value_agreement,NaN,agreement.escrowAmount.value,"decimal(38,16)",0,10c007ff9480e274d37d128ae6ba56c6,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
12,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,escrowBranchCode_agreement,NaN,agreement.escrowBranchCode,string,0,4e1397361e5d4777075abc02c69694a0,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
13,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,escrowId_agreement,NaN,agreement.escrowId,string,0,99ae37578a01d1df90ed51f45e456dc6,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
14,escrow_legal214_agreement_actual,None,None,escrow_id,escrow_legal214_agreement_actual_dto,escrow_id,NaN,NaN,string,0,d06ef84caa00e2ae905b0b57e691392e,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
15,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,estateObject_ExpireDate_agreementObject,NaN,agreementObject.estateObjectExpireDate,date,0,ef1377661c530f135758e8f6235e3fa6,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
16,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,expireDate_agreementObject,NaN,agreementObject.expireDate,date,0,007dd282ed13ae3f743ac78f54b31381,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
17,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,externalRegistryId_escrow_accountDetails,NaN,accountDetails.escrowAccount.externalRegistryId,string,0,6cc0c548293b13dbad15c8e2d17cc027,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
18,escrow_legal214_agreement_actual,None,None,headers,escrow_legal214_agreement_actual_dto,headers,NaN,NaN,string,0,02db06972c80124cec100752f7d523b4,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
19,escrow_legal214_agreement_actual,None,None,id,escrow_legal214_agreement_actual_dto,id,NaN,NaN,BIGINT,0,e963d895eedb28b87266260109e1f042,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
20,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,lastModifiedDate_agreement,NaN,agreement.lastModifiedDate,timestamp,0,6c8048f44be319587b151310dfdd8919,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
21,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,legalEpkId_beneficiary,NaN,beneficiary.legalEpkId,string,0,ab1fe4d8d5da9b8cd558ac567f0ec28c,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
22,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,legalEpkId_deponent,NaN,deponent.legalParty.legalEpkId,string,0,9937345e3a9676a6cc41f941e832f452,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
23,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,legalName_beneficiary,NaN,beneficiary.legalName,string,0,efe3ced1f7aba2c0766c5f324ec6c20c,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
24,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,legalName_deponent,NaN,deponent.legalParty.legalName,string,0,861012bbca1661a8674120ee99fa8c5d,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
25,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,number_escrow_accountDetails,NaN,accountDetails.escrowAccount.number,string,0,1a683fc4d209b71e0f439940ec279f65,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
26,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,openDate_accountDetails,NaN,accountDetails.openDate,date,0,99b16bbdcaeaefe945090cb4dea49423,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
27,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,openDate_agreement,NaN,agreement.openDate,date,0,bc57e45753b2cfa935a2d33e75f4cf45,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
28,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,parentAgreementId_agreement,NaN,agreement.parentAgreementId,string,0,76d888debd49580e388591e808f13116,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
29,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,rateSubsidyScheme_agreement,NaN,agreement.rateSubsidyScheme,string,0,427e4fc7478065b344a5af32b60188bc,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
30,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,reference_agreement,NaN,agreement.reference,string,0,63c039a572b473800a8c002aaaeb2740,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
31,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,registryTypeCode_accountDetails,NaN,accountDetails.registryTypeCode,string,0,7218c32270c26367635fb5f98639bcc2,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
32,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,registryTypeName_accountDetails,NaN,accountDetails.registryTypeName,string,0,5ec477df6513da7670f0102a512aa01c,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
33,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,status_agreement,NaN,agreement.status,string,0,3074ec6a77abc4ade6df6c6c26d913bd,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
34,escrow_legal214_agreement_actual,None,None,sys_date_create_or_update,escrow_legal214_agreement_actual_dto,sys_date_create_or_update,NaN,NaN,timestamp,0,18685a0756587ad48c045fe89466361b,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
35,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,taxId_beneficiary,NaN,beneficiary.taxId,string,0,5c5c0d566b7989816964c2e2dd7b025f,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
36,escrow_legal214_agreement_actual,None,None,dto,escrow_legal214_agreement_actual_dto,taxId_deponent,NaN,deponent.legalParty.taxId,string,0,9d16f5295278e6c8de3b8aab9a8e3670,0d24e60bed20cc90a26e9a060676644d,e2e08633e679d4a8deec906a3e08f2cd
37,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,beneficiaryBankBranch,NaN,agreement.beneficiaryBankBranch,string,0,f6e77c6e41397f4745154c41f8cca914,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
38,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,beneficiarybankregionalunit,NaN,agreement.beneficiaryBankRegionalUnit,string,0,f8c05cd1d47225658c8c4e5307970294,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
39,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,closedate,NaN,accounts.closeDate,date,0,5186a950addc865056810c1bf42783e2,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
40,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,conclusiondate,NaN,accounts.conclusionDate,date,0,5074733aec349750b151f73d8b46b158,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
41,escrow_legalgk_agreement_actual,None,None,deleted,escrow_legalgk_agreement_actual_dto,deleted,NaN,NaN,boolean,0,d746ecdf543ae813da80b642145f05e0,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
42,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,deponentBankBranch,NaN,agreement.deponentBankBranch,string,0,04487d675c559ada41a2b3131acc54bf,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
43,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,deponentBankRegionalUnit,NaN,agreement.deponentBankRegionalUnit,string,0,13799959b085d3eac993d28e279769d8,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
44,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositWithdrawalDate,NaN,agreement.depositWithdrawalDate,date,0,d018e989d543f640cd1bf446f8c13444,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
45,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositorlegal_creditcontract_date,NaN,depositorLegal.creditContract.date,date,0,034dca206707c2b5f358b1fff1bd599c,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
46,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositorlegal_creditcontract_eks,NaN,depositorLegal.creditContract.crmId,string,0,77ca0c2e868623ebaac3622c2d81ea03,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
47,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositorlegal_creditcontract_kulid,NaN,depositorLegal.creditContract.contractId,string,0,3c3445d2fa1a1fda69c1a8bce287fbfb,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
48,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositorlegal_creditcontract_number,NaN,depositorLegal.creditContract.number,string,0,28ca11ad1c62fc2bd1f91a224762da38,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73
49,escrow_legalgk_agreement_actual,None,None,dto,escrow_legalgk_agreement_actual_dto,depositorlegal_epkid,NaN,depositorLegal.epkId,string,0,28c8526c512ee717e58c616f8d10d541,65034a40725128bac8c87340c371adf6,3b9c3bdd93def3bf38a8914b95187a73

column_mappings rows missing source_tables or target_tables (should be 0): 0
enriched rows with Excel column lineage: 848 of 1232

,excel_sheet,column_index,excel_column_flat,source_table,source_column,target_table,target_column,mapping_id,transformation_rule
0,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,agreementReference,9204734d83f71ec9a9c72d78a26bfb0b,agreementReference
1,NaN,NaN,NaN,percent_payment,deleted,percent_payment_dto,deleted,0f34132456b58f8b6bdf9e796032d74f,NaN
2,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,eventStatus,4b466f7dc83bcab301c8766fc8ac90e1,eventStatus
3,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,factoryId,b7abbd98b103e5d40074713a08eff055,factoryId
4,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,feeEventType_code,be97c3958401c6c3256bab1332bfadac,feeEventType.code
5,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,feeEventType_description,5fcdb9b786e5101946abbf61cff69877,feeEventType.description
6,NaN,NaN,NaN,percent_payment,id,percent_payment_dto,id,0d73ebd55abeb836d2895d522bff23b8,NaN
7,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_dateFrom,6e42f45ef4d074cd71a0885604670b61,scheduleEntry.dateFrom
8,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_dateTill,c6bdf6a83ea94b907336e6fa93f79228,scheduleEntry.dateTill
9,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_scheduleAmount_currency,6e575c2e826827a244ca7fcf20402dd7,scheduleEntry.scheduleAmount.currency
10,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_scheduleAmount_value,52513660cb165076a322e6fa47600067,scheduleEntry.scheduleAmount.value
11,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_scheduleDate,3290247870d9d3130989cb05576d2dc3,scheduleEntry.scheduleDate
12,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_status_code,d2730b4d6a5de9dfaf25de1f5fbe213a,scheduleEntry.status.code
13,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_status_description,4231cb61191e58e181f321475f2e9ddc,scheduleEntry.status.description
14,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_type_code,e9dd605433bec026bbca540eb642c854,scheduleEntry.type.code
15,NaN,NaN,NaN,percent_payment,dto,percent_payment_dto,scheduleEntry_type_description,e4ea4b3d4e06953d0909ddd36db9bd26,scheduleEntry.type.description
16,NaN,NaN,NaN,percent_payment,sys_date_create_or_update,percent_payment_dto,sys_date_create_or_update,e3d0aafbcbd998d2ffa3a41095a9c668,NaN
17,NaN,NaN,NaN,(target catalog),NaN,t_accred_cover_type,accred_cover_type_cd,10687ba88fbb5a8d300f316216534f22,NaN
18,NaN,NaN,NaN,(target catalog),NaN,t_accred_cover_type,accred_cover_type_id,ecdb935ed07c88e1e5c07f1ddaff5b94,NaN
19,NaN,NaN,NaN,(target catalog),NaN,t_accred_cover_type,accred_cover_type_name,574e04df50cbf03f6aefb29ae8ca4671,NaN
20,NaN,NaN,NaN,(target catalog),NaN,t_accred_cover_type,host_accred_cover_type_id,33d6566b4069d3f120209d7a38396b94,NaN
21,NaN,NaN,NaN,(target catalog),NaN,t_accred_income_scheme,accred_income_scheme_cd,7f1fa33d2277e9ce1401c233ba0ff02a,NaN
22,NaN,NaN,NaN,(target catalog),NaN,t_accred_income_scheme,accred_income_scheme_id,9ba06c9656228099c70a342401505542,NaN
23,NaN,NaN,NaN,(target catalog),NaN,t_accred_income_scheme,accred_income_scheme_name,234c4ed7e7766b7615e98d2c21c74a59,NaN
24,NaN,NaN,NaN,(target catalog),NaN,t_accred_income_scheme,host_accred_income_scheme_id,13eaa4b41edaf005abf95367ae5bad38,NaN
25,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,agr_accred_add_txt,1c31afa59c3dee12c4344b8514a7716c,NaN
26,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,agr_accred_id,1e3f286323c211a171290da39e4dfae8,NaN
27,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,agr_accred_num,e1f593421f3d25eb30600d2931bfd19f,NaN
28,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,agr_accred_type_id,6d58bd88c0f2f7441d81dfc86ccb3312,NaN
29,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,agr_frame_id,4f07c3007c4ac1ce55be153cf053daa4,NaN
30,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,close_dt,135539dd5bfeae6a1f8e1b59a0a87e6e,NaN
31,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,crncy_id,53d9240ec20b21137606eec06b54c06b,NaN
32,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,expiration_dt,f684ca65b966565d6b20aec0b5c8a33d,NaN
33,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,host_agr_accred_id,3ce387e5c50eac0a62727d82cfaed63e,NaN
34,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,issuer_agr_num,f329613188877a6f34d9c7bb11c3aebb,NaN
35,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred,open_dt,966140423d47cc38e35c0f85a237f0aa,NaN
36,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_add_type,agr_accred_add_type_cd,9e055a0f1371d479986d1acea0028faa,NaN
37,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_add_type,agr_accred_add_type_id,8fe2f2b634cb737b8a0f37dca32295d4,NaN
38,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_add_type,agr_accred_add_type_name,b9e521c8cff851406e2c10e5c33029f6,NaN
39,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,addendum_id,42b76dd25d19970d4bfb925c29709f5a,NaN
40,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,addendum_type_id,ad8e39937a4f690f761d1c902c2ed806,NaN
41,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,agr_accred_id,8fa65927f695a97ea5eefdfe02fbebe4,NaN
42,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,close_dt,16d5282bfd505524a464626a6b5f896f,NaN
43,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,expiration_dt,b155a4698e1c454f7682a371418d53c0,NaN
44,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,host_addendum_id,19fcee6e20cb2ff81ec690b91ff4fdaf,NaN
45,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,open_dt,2e252ff02113155e03e2fa9b9cdbc99d,NaN
46,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_addendum,signed_dt,a8f190fecc3a8c1657e3cc618972d2a9,NaN
47,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_agr_cred,agr_accred_id,8a30baa115f207d44fe3ee2fa690c798,NaN
48,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_agr_cred,agr_cred_id,1a366182221f05c802efb28162a3392b,NaN
49,NaN,NaN,NaN,(target catalog),NaN,t_agr_accred_agr_cred,end_dt,ffb4bd23c631a56991dc15b6ca4ae173,NaN

## Embeddings (`entity_type` mix + orphan `entity_id` vs `columns`)

In [27]:
emb_by_type = pd.read_sql_query(
    "SELECT entity_type, COUNT(*) AS n FROM embeddings GROUP BY entity_type ORDER BY n DESC",
    conn,
)
display(emb_by_type)

_emb_tot = pd.read_sql_query("SELECT COUNT(*) AS n FROM embeddings", conn).iloc[0]["n"]
_emb_hit = pd.read_sql_query(
    """
    SELECT COUNT(*) AS n FROM embeddings e
    WHERE EXISTS (SELECT 1 FROM columns c WHERE c.column_hash = e.entity_id)
    """,
    conn,
).iloc[0]["n"]
print(
    "embeddings whose entity_id matches a columns.column_hash:",
    f"{_emb_hit}/{_emb_tot}" if _emb_tot else "0/0",
)

emb_orphan_typed_column = pd.read_sql_query(
    """
    SELECT COUNT(*) AS n FROM embeddings e
    WHERE LOWER(e.entity_type) = 'column'
      AND NOT EXISTS (SELECT 1 FROM columns c WHERE c.column_hash = e.entity_id)
    """,
    conn,
).iloc[0]["n"]
print(
    "embeddings typed 'column' with no matching columns.column_hash:",
    int(emb_orphan_typed_column),
)

Empty DataFrame
Columns: [entity_type, n]
Index: []

embeddings whose entity_id matches a columns.column_hash: 0/0
embeddings typed 'column' with no matching columns.column_hash: 0

## Per-file rollup (excel uploads)

In [28]:
files_rollup = pd.read_sql_query(
    """
    SELECT
        f.file_hash,
        f.filename,
        f.model_used,
        f.upload_time,
        CASE WHEN f.summary IS NOT NULL AND TRIM(f.summary) != '' THEN 1 ELSE 0 END AS has_summary,
        CASE WHEN f.result_json IS NOT NULL AND TRIM(f.result_json) != '' THEN 1 ELSE 0 END AS has_result_json,
        (SELECT COUNT(*) FROM sheets sh WHERE sh.file_hash = f.file_hash AND IFNULL(sh.skipped, 0) = 0)
            AS sheets_loaded,
        (SELECT COUNT(*) FROM sheets sh WHERE sh.file_hash = f.file_hash AND IFNULL(sh.skipped, 0) != 0)
            AS sheets_skipped,
        (SELECT COUNT(DISTINCT c.column_hash)
         FROM sheets sh JOIN columns c ON c.sheet_hash = sh.sheet_hash
         WHERE sh.file_hash = f.file_hash AND IFNULL(sh.skipped, 0) = 0
        ) AS column_count,
        (SELECT COUNT(*)
         FROM data d
         JOIN sheets sh ON sh.sheet_hash = d.sheet_hash
         WHERE sh.file_hash = f.file_hash AND IFNULL(sh.skipped, 0) = 0
        ) AS cell_count
    FROM files f ORDER BY COALESCE(f.upload_time, '') DESC
    """,
    conn,
)
files_rollup

,file_hash,filename,model_used,upload_time,has_summary,has_result_json,sheets_loaded,sheets_skipped,column_count,cell_count
0,1c5bf176656a2076954c34f6777b972f,S2T_308_000046_v0.39.xlsx,GigaChat-Pro,2026-05-08T06:42:17.549431,1,1,9,1,96,17620

## Samples (first 8 rows each)

In [29]:
for t in EXPECTED_TABLES:
    try:
        sample = pd.read_sql_query(f'SELECT * FROM "{t}" LIMIT 8', conn)
    except Exception as exc:  # noqa: BLE001
        print(t, "->", exc)
        continue
    print("\n===", t, "===")
    display(sample)

=== files ===

,file_hash,filename,model_used,upload_time,summary,result_json
0,1c5bf176656a2076954c34f6777b972f,S2T_308_000046_v0.39.xlsx,GigaChat-Pro,2026-05-08T06:42:17.549431,Файл представляет собой детальную документацию...,"{""filename"": ""S2T_308_000046_v0.39.xlsx"", ""mod..."

=== sheets ===

,sheet_hash,file_hash,sheet_name,header_start_row,header_rows_count,nested_structure,skipped,skip_reason
0,fa828d25e9d8cda92801e4434ec7fc04,1c5bf176656a2076954c34f6777b972f,Список изменений,0,1,0,0,None
1,b267fb38b56b592db97308cc85fdedf7,1c5bf176656a2076954c34f6777b972f,S2T,1,1,0,0,None
2,9c193ba4cdbfd478947ca7fa2e4e03aa,1c5bf176656a2076954c34f6777b972f,Source columns,1,1,0,0,None
3,0c0d0e767120f823e343688e293b72f5,1c5bf176656a2076954c34f6777b972f,Target tables,1,1,0,0,None
4,74571462e568c6d6a3bff39e62d604e0,1c5bf176656a2076954c34f6777b972f,Target columns,1,1,0,0,None
5,ca72e10ff814d62c429d163e2a79085d,1c5bf176656a2076954c34f6777b972f,Метаданные для hadoop,0,1,0,0,None
6,4edffa608c3c29ab8b5e5957b8ba08c0,1c5bf176656a2076954c34f6777b972f,hadoop ->A,0,1,0,0,None
7,abd42ca3629e52d0c4e113151356df7b,1c5bf176656a2076954c34f6777b972f,А-слой->В-слой->S-слой,0,2,1,0,None

=== columns ===

,column_hash,sheet_hash,column_index,column_name_flat,column_header
0,a467e8dea059cf8f6fb908e1d3765b93,fa828d25e9d8cda92801e4434ec7fc04,0,Версия,Версия
1,ffc5ff8909f631e816946cb87253a7e5,fa828d25e9d8cda92801e4434ec7fc04,1,Дата,Дата
2,2894a2372dde3470254a342e6179483a,fa828d25e9d8cda92801e4434ec7fc04,2,Измененный объект,Измененный объект
3,b82e4b5224073ce6b91b6e7f73b7917a,fa828d25e9d8cda92801e4434ec7fc04,3,Изменение,Изменение
4,689b341a5fc1ea9f408f2e0163b05313,fa828d25e9d8cda92801e4434ec7fc04,4,Автор,Автор
5,7d30b5f3d2fe84bebab2a82714240a98,fa828d25e9d8cda92801e4434ec7fc04,5,Комментарий,Комментарий
6,0fe1e272c8654c6faf041204a2fbd761,fa828d25e9d8cda92801e4434ec7fc04,6,Номер патча,Номер патча
7,017b051377b7cb5c3c17b415727443b7,b267fb38b56b592db97308cc85fdedf7,0,№ ПП,№ ПП

=== data ===

,id,sheet_hash,row_num,column_hash,value
0,3b7cf286a653d850cacc893bb54150a0,fa828d25e9d8cda92801e4434ec7fc04,0,a467e8dea059cf8f6fb908e1d3765b93,0.5
1,8f496ccec03add2b75fc0f8a770e9fa0,fa828d25e9d8cda92801e4434ec7fc04,0,ffc5ff8909f631e816946cb87253a7e5,2024-09-30 00:00:00
2,ac93e41027f82dba6dad06a770bc6a36,fa828d25e9d8cda92801e4434ec7fc04,0,2894a2372dde3470254a342e6179483a,"S2T, Source columns, Target tables, Target col..."
3,694c3cb59b27653f81ed7798e1fd4119,fa828d25e9d8cda92801e4434ec7fc04,0,b82e4b5224073ce6b91b6e7f73b7917a,"Добавлен атрибут в t_registry, добавлена табли..."
4,b11e144b728184312284d48cd4e8bbd4,fa828d25e9d8cda92801e4434ec7fc04,0,689b341a5fc1ea9f408f2e0163b05313,Свиридова
5,b48f49ef4fc99d382cb1b0b4a79000fa,fa828d25e9d8cda92801e4434ec7fc04,1,a467e8dea059cf8f6fb908e1d3765b93,0.6
6,94d87f2c1d2add63a60cccc0a0701e61,fa828d25e9d8cda92801e4434ec7fc04,1,ffc5ff8909f631e816946cb87253a7e5,2024-10-08 00:00:00
7,507b39aa4c1c333f6fcf999e0f0f3967,fa828d25e9d8cda92801e4434ec7fc04,1,2894a2372dde3470254a342e6179483a,"S2T, Additional objects"

=== relationships ===

,id,from_id,to_id,relation_type,metadata
0,8e3c7506569fad771ff384415447ae20,0b300e03096ac6fc93c626b830602202,06f7ae4e4cc0af0bcceeaf6036ac76c0,MAPS_TO,"{""transformation"": ""direct""}"
1,11521704d2bf2c30f20aa0b1b503e847,06f7ae4e4cc0af0bcceeaf6036ac76c0,0b300e03096ac6fc93c626b830602202,DERIVED_FROM,NaN
2,e3a055bf97882fbab567e48c8da05f9a,ab4e32d03e12ae55c374a2306a99c231,923780c521e841ef007476f2113f9250,MAPS_TO,"{""transformation"": ""direct""}"
3,7f692a3c59b56e6e16a4a144937b4cd3,923780c521e841ef007476f2113f9250,ab4e32d03e12ae55c374a2306a99c231,DERIVED_FROM,NaN
4,ca6b243a7a0082ee43153d40a061cb44,9da9a9872f06e5d0566a25c3ec4ea318,9474bdf9b4c7eb08743443459ab1b648,MAPS_TO,"{""transformation"": ""direct""}"
5,30ed33344c284509ac8eec7aa0eb1030,9474bdf9b4c7eb08743443459ab1b648,9da9a9872f06e5d0566a25c3ec4ea318,DERIVED_FROM,NaN
6,8d0e2f5a80a2aff3d571bfdbd46db859,82fec8e22058094f7730b7d2b5911f11,7e87e9306830935cc2273215a907c1a8,MAPS_TO,"{""transformation"": ""direct""}"
7,808649dd640c6c47a2bcc62c5381d1b3,7e87e9306830935cc2273215a907c1a8,82fec8e22058094f7730b7d2b5911f11,DERIVED_FROM,NaN

=== embeddings ===

Empty DataFrame
Columns: [id, entity_id, entity_type, vector]
Index: []

=== source_tables ===

,id,name,description,system_code
0,2b4ea93267ae9196aff4eb241f3be1f0,b3080000460001_escrow_legal214_agreement_actua...,None,None
1,fe8927df7669eae62eeb5e5e2b52c6a3,ETL,None,None
2,1cd615e1000c37daeb56921d1226bf2d,b3080000460002_escrow_legalgk_agreement_actual...,None,None
3,e02f2ef208ddc77a90dc7c267000c690,b3080000460003_escrow_legalgk_beneficiariesind...,None,None
4,9f1a4fb4a3f2790bbdce0f27bad3e347,b3080000460004_escrow_legalgk_beneficiarieslegal,None,None
5,ac02212c483ea5278cce612d4cb1a2b9,b3080000460009_general_agreement_actual_dto,None,None
6,6800848b7b040f506883bdb5f5dc869e,b3080000460008_general_agreement_actual_limits...,None,None
7,0a19d4b287cfdc01b2b860ef3cd7d6a7,b3080000460015_lcl_agreement_actual_dto,None,None

=== target_tables ===

                                 id                   name description
0  fc59e0ebae51e1da89c9fb681d56e789           t_agr_escrow        None
1  930ceabc2e8d15595e4fa858459a5c46             t_agr_cred        None
2  b6961befb46f71c52bdc45a48b7c4779             t_registry        None
3  c7747290c3743a72c849213b46e0561b        t_escrow_scheme        None
4  7eee79f5ce2ef1b69ccabd3fac3fcd0a  t_agr_escrow_agr_cred        None
5  db4e667c61bb7176619f8fd931cc0492      t_agr_escrow_cust        None
6  6ef3c773274277113f564a32873ce068                 t_cust        None
7  6f9af27785c7638059a2ac323fec4fc3              t_int_org        None

=== column_mappings ===

,id,target_table_id,target_column,source_table_id,source_column,transformation_rule,data_type,is_primary_key
0,57b8ed4ac45da528f3235366d87a1834,fc59e0ebae51e1da89c9fb681d56e789,agr_escrow_id,2b4ea93267ae9196aff4eb241f3be1f0,Идентификатор договора эскроу,escrowId_agreement_uid,UUID,1
1,d97a0665f55b96465cecbac1ef60e9ea,fc59e0ebae51e1da89c9fb681d56e789,open_dt,2b4ea93267ae9196aff4eb241f3be1f0,Дата открытия договора эскроу,openDate_agreement,DATE,0
2,3825bf1df79d7fc941221863b9792157,fc59e0ebae51e1da89c9fb681d56e789,signed_dt,2b4ea93267ae9196aff4eb241f3be1f0,Дата открытия договора эскроу,openDate_agreement,DATE,0
3,ae32f6764c69c45762ec28ae898e5093,fc59e0ebae51e1da89c9fb681d56e789,close_dt,2b4ea93267ae9196aff4eb241f3be1f0,Дата закрытия договора эскроу,closeDate_agreement,DATE,0
4,32f752a6d08753e0c3755f90dac29d78,fc59e0ebae51e1da89c9fb681d56e789,agr_escrow_num,2b4ea93267ae9196aff4eb241f3be1f0,Номер договора,reference_agreement,TEXT,0
5,8b9b69e0881dfb11b99bc550567bc1a2,fc59e0ebae51e1da89c9fb681d56e789,host_agr_escrow_id,2b4ea93267ae9196aff4eb241f3be1f0,Идентификатор договора эскроу,escrowId_agreement,TEXT,0
6,7a32f922f2751603d3d65663ba5493e5,fc59e0ebae51e1da89c9fb681d56e789,permission_explotation_plan_dt,2b4ea93267ae9196aff4eb241f3be1f0,Плановая дата ввода ОС в эксплуатацию,completeEstimateDate_agreementObject,DATE,0
7,d691250c190401cf6634baa6d645c0f3,fc59e0ebae51e1da89c9fb681d56e789,depositing_object_dt,2b4ea93267ae9196aff4eb241f3be1f0,Срок депонирования объекта,estateObject_ExpireDate_agreementObject,DATE,0

=== additions ===

,id,table_name,table_description,source_tables_name,sql,description
0,8f6e0bc62f923ffebb0647c5248aa0fb,None,Снимок-снимок,a_000046_escrow_legal214_agreement_actual_dto_...,None,a_000046_escrow_legal214_agreement_actual_dto
1,d1af9b3547314ab2684276bff2bc33b9,None,Снимок-снимок,a_000046_escrow_legalgk_agreement_actual_dto_s...,None,a_000046_escrow_legalgk_agreement_actual_dto
2,8c6d40937872a281b6aa2aeea1bfe528,None,Снимок-снимок,a_000046_escrow_legalgk_beneficiariesindividualс,None,a_000046_escrow_legalgk_beneficiariesindividual
3,53517ed58d5ff4530c53611e2ac12f86,None,Снимок-снимок,a_000046_escrow_legalgk_beneficiarieslegal_snp...,None,a_000046_escrow_legalgk_beneficiarieslegal
4,37c6ebb39b881be4815fb6b8c5a8a114,None,Снимок-снимок,a_000046_escrow_legalgk_tariffs_snp_ext,None,a_000046_escrow_legalgk_tariffs
5,23ed8fda03ef6856d01765ab98f2d1f4,None,Снимок-снимок,a_000046_payments_2_0_posting_dto_snp_ext,None,a_000046_payments_2_0_posting_dto
6,f02181eaa956a7e30e95d9c45e719828,None,Снимок-снимок,a_000046_general_agreement_actual_dto_snp_ext,None,a_000046_general_agreement_actual_dto
7,8d60b6805a741cfbc8ef672e714895d9,None,Снимок-снимок,a_000046_general_agreement_actual_limitschedul...,None,a_000046_general_agreement_actual_limitschedule

In [30]:
conn.close()
print("Read-only connection closed.")

Read-only connection closed.